/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package io.vov.vitamio.demo;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int mediacontroller_bg=0x7f050002;
        public static final int mediacontroller_bg_pressed=0x7f050001;
        public static final int transparent=0x7f050000;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int mediacontroller_button=0x7f020001;
        public static final int mediacontroller_pause=0x7f020002;
        public static final int mediacontroller_play=0x7f020003;
        public static final int mediacontroller_screen_fit=0x7f020004;
        public static final int mediacontroller_screen_size=0x7f020005;
        public static final int mediacontroller_sreen_size_100=0x7f020006;
        public static final int mediacontroller_sreen_size_crop=0x7f020007;
        public static final int scrubber_control_disabled_holo=0x7f020008;
        public static final int scrubber_control_focused_holo=0x7f020009;
        public static final int scrubber_control_normal_holo=0x7f02000a;
        public static final int scrubber_control_pressed_holo=0x7f02000b;
        public static final int scrubber_control_selector_holo=0x7f02000c;
        public static final int scrubber_primary_holo=0x7f02000d;
        public static final int scrubber_progress_horizontal_holo_dark=0x7f02000e;
        public static final int scrubber_secondary_holo=0x7f02000f;
        public static final int scrubber_track_holo_dark=0x7f020010;
    }
    public static final class id {
        public static final int buffer=0x7f08000f;
        public static final int button1=0x7f080015;
        public static final int dd=0x7f08000c;
        public static final int download_rate=0x7f080011;
        public static final int load_rate=0x7f080012;
        public static final int localaudio=0x7f080009;
        public static final int localvideo=0x7f080006;
        public static final int localvideo_setsurface=0x7f080007;
        public static final int mediacontroller_file_name=0x7f080005;
        public static final int mediacontroller_play_pause=0x7f080001;
        public static final int mediacontroller_seekbar=0x7f080004;
        public static final int mediacontroller_time_current=0x7f080002;
        public static final int mediacontroller_time_total=0x7f080003;
        public static final int probar=0x7f080010;
        public static final int start=0x7f080014;
        public static final int streamvideo=0x7f080008;
        public static final int sub1=0x7f08000b;
        public static final int subtitle_view=0x7f08000e;
        public static final int surface=0x7f08000a;
        public static final int surface_view=0x7f08000d;
        public static final int textView=0x7f080000;
        public static final int url=0x7f080013;
    }
    public static final class layout {
        public static final int media_metadata=0x7f030000;
        public static final int mediacontroller=0x7f030001;
        public static final int mediaplayer_1=0x7f030002;
        public static final int mediaplayer_2=0x7f030003;
        public static final int mediaplayer_3=0x7f030004;
        public static final int subtitle1=0x7f030005;
        public static final int subtitle2=0x7f030006;
        public static final int videobuffer=0x7f030007;
        public static final int videoview=0x7f030008;
    }
    public static final class raw {
        public static final int test_cbr=0x7f040000;
    }
    public static final class string {
        public static final int VideoView_error_button=0x7f06000b;
        public static final int VideoView_error_text_invalid_progressive_playback=0x7f060009;
        public static final int VideoView_error_text_unknown=0x7f06000a;
        public static final int VideoView_error_title=0x7f060008;
        public static final int action_settings=0x7f060014;
        public static final int local_audio=0x7f060011;
        public static final int local_video=0x7f06000e;
        public static final int local_video_setsurface=0x7f06000f;
        public static final int mediacontroller_play_pause=0x7f06000c;
        public static final int openvideo1=0x7f06001b;
        public static final int openvideo2=0x7f06001c;
        public static final int permission_group_tools_description=0x7f060003;
        public static final int permission_group_tools_label=0x7f060002;
        public static final int permission_receive_messages_description=0x7f060005;
        public static final int permission_receive_messages_label=0x7f060004;
        public static final int permission_write_providers_description=0x7f060007;
        public static final int permission_write_providers_label=0x7f060006;
        public static final int res_audio=0x7f060012;
        public static final int stream_video=0x7f060010;
        public static final int subtitle1=0x7f060015;
        public static final int subtitle12=0x7f060016;
        public static final int title_activity_media_player_subtitle=0x7f060017;
        public static final int title_activity_video_buffer=0x7f06001a;
        public static final int title_activity_video_subtitle_demo=0x7f060013;
        public static final int title_activity_video_subtitle_list=0x7f060019;
        public static final int title_activity_video_view_subtitle=0x7f060018;
        public static final int vitamio_demo_name=0x7f06000d;
        public static final int vitamio_init_decoders=0x7f060001;
        public static final int vitamio_library_app_name=0x7f060000;
    }
    public static final class style {
        public static final int MediaController_SeekBar=0x7f070000;
        public static final int MediaController_Text=0x7f070001;
        public static final int NoActionBar=0x7f070002;
    }
}
